run1: 1.exe
	./1.exe

1.exe: 1.c 1.s
	gcc -o 1.exe 1.c 1.s

run2: 2.exe
	./2.exe

2.exe: 2.c 2.s
	gcc -o 2.exe 2.c 2.s

run3: 3.exe
	./3.exe

3.exe: 3.c 3.s
	gcc -o 3.exe 3.c 3.s

run4: 4.exe
	./4.exe

4.exe: 4.c 4.s
	gcc -o 4.exe 4.c 4.s

run5: 5.exe
	./5.exe

5.exe: 5.c 5.s
	gcc -o 5.exe 5.c 5.s

run6: 6.exe
	./6.exe

6.exe: 6.c 6.s
	gcc -o 6.exe 6.c 6.s

run7: 7.exe
	./7.exe

7.exe: 7.c 7.s
	gcc -o 7.exe 7.c 7.s

run8: 8.exe
	./8.exe

8.exe: 8.c 8.s
	gcc -o 8.exe 8.c 8.s

clean:
	rm -f *.exe
